[package]
name = "elucid-language"
version.workspace = true
edition.workspace = true

[dependencies]
ariadne = { workspace = true }
chumsky = { workspace = true }
logos = { workspace = true }

[dev-dependencies]
insta = { version = "1.44.3" }